version: "3"
services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=pedb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
  backend:
    build: backend
    volumes:
      - ./backend:/usr/local/PerkinElmer/backend/
    ports:
      - 8000:8000
  frontend:
    build: frontend
    volumes:
      - ./frontend/:/usr/local/PerkinElmer/frontend/
      - /usr/local/PerkinElmer/frontend/node_modules/
    ports:
      - 3000:3000
    depends_on:
      - backend
  nginx:
    image: nginx:1.15
    volumes:
      - ./config/pe-nginx.conf:/etc/nginx/conf.d/pe-nginx.conf
    ports:
      - 80:8080
    depends_on:
      - frontend